<template><div><h1 id="orangepi-pc" tabindex="-1"><a class="header-anchor" href="#orangepi-pc"><span>orangepi-pc</span></a></h1>
<h2 id="编译环境" tabindex="-1"><a class="header-anchor" href="#编译环境"><span>编译环境</span></a></h2>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">export</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> PATH</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">home</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">user</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">orangepi-pc</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">tools</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">gcc-arm-9</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">2-2019</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">12-x86_64-arm-none-linux-gnueabihf</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bin</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$PATH</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="uboot-编译" tabindex="-1"><a class="header-anchor" href="#uboot-编译"><span>uboot 编译</span></a></h2>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    make</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ARCH=arm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> CROSS_COMPILE=arm-none-linux-gnueabihf-</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  orangepi_pc_plus_defconfig</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    make</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ARCH=arm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> CROSS_COMPILE=arm-none-linux-gnueabihf-</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">  -j32</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="kernel-编译" tabindex="-1"><a class="header-anchor" href="#kernel-编译"><span>kernel 编译</span></a></h2>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> apt-get</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> liblz4-tool</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    make</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ARCH=arm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> CROSS_COMPILE=arm-none-linux-gnueabihf-</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   orangepi_defconfig</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    make</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ARCH=arm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> CROSS_COMPILE=arm-none-linux-gnueabihf-</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">  -j32</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="制作-boot-scr" tabindex="-1"><a class="header-anchor" href="#制作-boot-scr"><span>制作 boot.scr</span></a></h2>
<p fdt_addr_r="">新建文件 boot.cmd
输入
load mmc 0:1 ${kernel_addr_r} zImage;
load mmc 0:1 ${fdt_addr_r} sun8i-h3-orangepi-pc-plus.dtb;
bootz ${kernel_addr_r} - $</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> apt</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> dos2unix</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">dos2unix</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> boot.cmd</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> #转换成unix</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">mkimage</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -C</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> none</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -A</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> arm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -T</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> script</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -d</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> boot.cmd</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> boot.scr</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="制作img" tabindex="-1"><a class="header-anchor" href="#制作img"><span>制作img</span></a></h2>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">./genimage/genimage</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --input</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> input</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --output</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> images</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --config</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> root/genimage.cfg</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>setenv bootcmd 'fatload mmc 0 $kernel_addr_r zImage; fatload mmc 0 $fdt_addr_r sun8i-h3-orangepi-pc-plus.dtb; bootz $kernel_addr_r - $fdt_addr_r'</p>
<h2 id="uboot" tabindex="-1"><a class="header-anchor" href="#uboot"><span>uboot</span></a></h2>
<h2 id="文件系统制作" tabindex="-1"><a class="header-anchor" href="#文件系统制作"><span>文件系统制作</span></a></h2>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">cp</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -r</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> mkubuntu-2204/rootfs.ext4</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> mkimage/input/</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="进入系统" tabindex="-1"><a class="header-anchor" href="#进入系统"><span>进入系统</span></a></h2>
<p>配网</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">root@localhost:~#</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> history</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    1</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  lsmod</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    2</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">  -a</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    3</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  eth0</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> up</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    4</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  idmesg</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> grep</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> usb</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    5</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  dmesg</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> grep</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> usb</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    6</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  vim</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /etc/network/interfaces</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    7</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  eth0</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> up</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    8</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  route</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    9</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   10</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> eth0</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 192.168.0.1</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> netmask</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 255.255.255.0</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   11</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   12</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> eth0</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 192.168.1.100</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> netmask</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 255.255.255.0</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   13</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ifconfig</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   14</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  route</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> default</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gw</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 192.168.1.101</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   15</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  route</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> default</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gw</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 192.168.1.101</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> eth0</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   16</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ping</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> www.baidu.com</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   17</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  vim</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /etc/resolv.conf</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   18</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  systemctl</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> restart</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> networking</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   19</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  ping</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> www.baidu.com</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   20</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  sync</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   21</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  apt-get</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> alsa-utils</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   22</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  aplay</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -l</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">   23</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  history</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> vim</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /etc/network/interfaces</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">auto</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> eth0</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> #不加这句重启会需要重新up eth0</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">auto</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> eth0</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">iface</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> eth0</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> inet</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> static</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">address</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 192.168.1.100</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">netmask</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 255.255.255.0</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">gateway</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 192.168.1.101</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">dns-nameservers</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 192.168.1.101</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 8.8.8.8</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> #永久设置eth0的 dns</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">root@localhost:~</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="音频开发" tabindex="-1"><a class="header-anchor" href="#音频开发"><span>音频开发</span></a></h2>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">换源</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sed</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -e</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s|mirrors.dahuatech.com|mirrors.tuna.tsinghua.edu.cn|g</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -i.bak</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /etc/apt/sources.list</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">安装</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> RealtimeSTT</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 语音转文字</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pip3</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">  -i</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  RealtimeSTT</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">调节音频设备</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">alsamixer</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="swap-分区创建" tabindex="-1"><a class="header-anchor" href="#swap-分区创建"><span>swap 分区创建</span></a></h2>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> dd</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> if=/dev/zero</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> of=/swapfile</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> bs=1M</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> count=</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1024</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> chmod</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 600</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /swapfile</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">mkswap</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /swapfile</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">开启</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Swap</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> swapon</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /swapfile</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">到这里，Swap</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 已经开启成功。我们再次使用</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> free</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -m</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 命令查看一下，你将看到类似下面的输出。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">free</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -m</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">              total</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">        used</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">        free</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">      shared</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  buff/cache</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   available</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Mem:</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">          15881</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">       10110</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">        1238</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">        1535</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">        4532</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">        3641</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Swap:</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">          4978</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">         998</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">        3979</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">5设置系统启动时自动开启</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Swap</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">使用编辑器编辑</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /etc/fstab</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 文件，添加</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Swap</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 自动开启的配置，这里推荐使用</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gedit</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 进行编辑，也可以使用其他文本编辑工具，例如</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> nano。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 编辑这个文件需要管理员权限</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gedit</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /etc/fstab</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">在</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> fstab</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 文件最后一行添加下面的内容</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">/swapfile</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> none</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> swap</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> defaults</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


