export const themeData = {"locales":{"/":{"selectLanguageName":"简体中文","selectLanguageText":"选择语言","appearanceText":"外观","lightModeSwitchTitle":"切换为浅色主题","darkModeSwitchTitle":"切换为深色主题","outlineLabel":"此页内容","returnToTopLabel":"返回顶部","editLinkText":"编辑此页","contributorsText":"贡献者","prevPageLabel":"上一页","nextPageLabel":"下一页","lastUpdatedText":"最后更新于","changelogText":"变更历史","changelogOnText":"于","changelogButtonText":"查看全部变更历史","copyrightText":"版权所有","copyrightAuthorText":"版权归属：","copyrightCreationOriginalText":"本文链接：","copyrightCreationTranslateText":"本文翻译自：","copyrightCreationReprintText":"本文转载自：","copyrightLicenseText":"许可证：","notFound":{"code":"404","title":"页面未找到","quote":"但是，如果你不改变方向，并且一直寻找，最终可能会到达你要去的地方。","linkText":"返回首页"},"homeText":"首页","blogText":"博客","tagText":"标签","archiveText":"归档","categoryText":"分类","archiveTotalText":"{count} 篇","encryptButtonText":"确认","encryptPlaceholder":"请输入密码","encryptGlobalText":"本站只允许密码访问","encryptPageText":"本页面只允许密码访问","footer":{"message":"\n    Powered by \n    <a target=\"_blank\" href=\"https://gitee.com/unitedrhino/things/blob/master/LICENSE\">\n      云物通科技有限公司\n    </a> | \n    <a href=\"http://beian.miit.gov.cn/\" target=\"_blank\">\n      滇ICP备2024043132号-1\n    </a> | \n    <img src=\"/img/beian.png\" \n         style=\"width: 15px; vertical-align: middle; display: inline-block;\" />\n  "},"profile":{"avatar":"https://theme-plume.vuejs.press/plume.png","name":"联犀控制器","description":""},"sidebarScrollbar":true,"outline":"deep","aside":true,"bulletin":{"lifetime":"always","id":"1.3.0","content":"<div style=\"text-align:center\"><p><strong>赶快加微信关注最新进展及行业交流</strong></p>\n<img  src=\"/wx.jpg\">  \n</div><p><em>企业版限时优惠中,欢迎选购</em></p>\n"},"navbar":[{"text":"首页","link":"/","icon":"ic:round-home"},{"text":"硬件设备","icon":"mdi:hard-hat","items":[{"text":"联犀控制器","link":"/hardware/AxonCore/"}]},{"text":"开源软件","icon":"mdi:open-source","items":[{"text":"linuxcnc","link":"/soft/linuxcnc/"}]},{"text":"文档","icon":"mdi:book-open-page-variant","items":[{"text":"用户手册","link":"/doc/user/"},{"text":"开发手册","link":"/doc/develop/system.md"}]},{"text":"关于我们","link":"/about/"},{"text":"联系我们","link":"/contact/"}]}},"appearance":true,"blog":false,"navbarSocialInclude":["github","twitter","discord","facebook"],"aside":true,"outline":[2,3],"externalLinkIcon":true,"editLink":true,"prevPage":true,"nextPage":true,"footer":{"message":"\n    Powered by \n    <a target=\"_blank\" href=\"https://gitee.com/unitedrhino/things/blob/master/LICENSE\">\n      云物通科技有限公司\n    </a> | \n    <a href=\"http://beian.miit.gov.cn/\" target=\"_blank\">\n      滇ICP备2024043132号-1\n    </a> | \n    <img src=\"/img/beian.png\" \n         style=\"width: 15px; vertical-align: middle; display: inline-block;\" />\n  "},"contributors":true,"changelog":true,"bulletin":{"lifetime":"always","id":"1.3.0","content":"<div style=\"text-align:center\"><p><strong>赶快加微信关注最新进展及行业交流</strong></p>\n<img  src=\"/wx.jpg\">  \n</div><p><em>企业版限时优惠中,欢迎选购</em></p>\n"}}

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
